import { readFile } from "node:fs/promises";
import path from "node:path";
import { THRESHOLDS } from "@/engine/config";
import { loadArtifacts } from "@/lib/artifacts";
import { mult } from "@/lib/format";

export const dynamic = "force-static";

interface RecoveryArtifact {
  value_corr: number;
  conv_corr: number;
  negative_control_corr: number;
  calibration: { overall: number; by_stratum: Record<string, number> };
  table: {
    dim: string;
    level: string;
    n: number;
    effect_value_usd: number;
    planted_ln_m_ltv: number;
  }[];
}

export default async function MethodologyPage() {
  const data = await loadArtifacts();
  const recovery = JSON.parse(
    await readFile(path.join(process.cwd(), "data", "artifacts", "recovery.json"), "utf8"),
  ) as RecoveryArtifact;
  const v = data.meta.validate;

  return (
    <div className="max-w-3xl space-y-10">
      <header className="space-y-3">
        <h1 className="font-display text-3xl">Can I believe this number?</h1>
        <p className="text-muted leading-relaxed">
          Every number on this dashboard is synthetic — generated by a seeded, fully documented
          process. That is not a caveat buried in a footer; it is the design. The generator plants
          known effects, the pipeline never gets to see them, and this page shows you how well it
          recovered them anyway. Transparency is the product.
        </p>
      </header>

      <Section title="The data, honestly">
        <P>
          ~{Math.round(data.rows.find((r) => r.grain === "global")!.n_subs / 1000)}k synthetic
          subscribers over 18 weekly cohorts across 4 platforms, ~200 Zipf-weighted campaigns and 10
          targeting dimensions. Two stories are planted on purpose: <b>the flip</b> (a cell the
          platform pixel calls a ~2× winner that truly returns ~$0.40 per dollar — impulse buyers
          take a $99 one-time offer inside the 7-day attribution window, then refund and never
          renew) and <b>the untapped cell</b> (high composed value, deliberately starved of budget).
          The full answer key — every planted multiplier — ships in{" "}
          <code className="text-untapped">truth_effects.json</code>. An import-graph test asserts
          the model, cube and query code never read it.
        </P>
      </Section>

      <Section title="How a prediction is made (in plain English)">
        <Ol
          items={[
            <>
              <b>Chance they ever buy × what buyers like them spend.</b> Two simple models over each
              subscriber&apos;s first-week behavior and acquisition traits, trained only on cohorts
              old enough that their 90-day outcome is already known.
            </>,
            <>
              <b>Scaled to average out correctly.</b> Predictions are calibrated against known
              cohorts, separately for whale-eligible audiences. Out-of-sample the totals land within{" "}
              {pctOff(recovery.calibration.overall)} of reality (band ±10%).
            </>,
            <>
              <b>Thin cells borrow from their parent.</b> Weight = k/(k+n) with k=
              {THRESHOLDS.k_shrink}: a cell needs about {THRESHOLDS.k_shrink} subscribers to mostly
              stand on its own; below that it leans on its campaign, audience or platform. The UI
              shows this as &ldquo;% borrowed&rdquo;.
            </>,
            <>
              <b>Every estimate carries an 80% uncertainty range,</b> and verdicts gate on the range
              bound — never the point estimate. KILL means <i>even the best case loses</i>; SCALE
              means <i>even the worst case clears break-even with margin</i>.
            </>,
          ]}
        />
      </Section>

      <Section title="Why the pixel lies (the mechanism, not an accusation)">
        <P>
          Ad platforms attribute <b>gross purchases inside a ~7-day window</b> and then go blind.
          They never see refunds, missed renewals, or the $2k managed-money sale that lands on day
          60. In a business where the front end breaks even and the back end pays, that window
          censors exactly the revenue that matters. A cell full of impulse buyers looks brilliant to
          the pixel; a slow, valuable retirement-education cell looks weak. The tool&apos;s only job
          is to close that gap — per cell, with receipts.
        </P>
      </Section>

      <Section title="The recovery proof">
        <P>
          The pipeline is scored against ground truth it never reads, under structure the model
          cannot represent (whale gating, zero-inflation, refund dynamics, heavy tails, censoring).
          Recovery validates <i>pipeline correctness</i>, not model-family choice:
        </P>
        <div className="grid grid-cols-3 gap-3 my-4">
          <Metric label="Value effects recovered" value={recovery.value_corr.toFixed(2)} sub="corr vs planted ln(m_ltv), materially planted levels" />
          <Metric label="Conversion effects recovered" value={recovery.conv_corr.toFixed(2)} sub="corr vs planted ln(m_feconv)" />
          <Metric label="Negative control" value={recovery.negative_control_corr.toFixed(2)} sub="corr vs a PERMUTED answer key — should be ≈ 0" />
        </div>
        <div className="rounded-lg border border-line overflow-hidden">
          <table className="w-full text-xs">
            <thead>
              <tr className="bg-surface text-left text-faint">
                <th className="px-3 py-2">trait</th>
                <th className="px-3 py-2 text-right">planted (ln m, centered)</th>
                <th className="px-3 py-2 text-right">recovered ($/buyer)</th>
                <th className="px-3 py-2 text-right">n</th>
              </tr>
            </thead>
            <tbody>
              {recovery.table
                .filter((r) => Math.abs(r.planted_ln_m_ltv) >= 0.15)
                .sort((a, b) => b.planted_ln_m_ltv - a.planted_ln_m_ltv)
                .map((r) => (
                  <tr key={`${r.dim}:${r.level}`} className="border-t border-line/50">
                    <td className="px-3 py-1.5 text-muted">
                      {r.dim}: <span className="text-foreground">{r.level}</span>
                    </td>
                    <td className={`px-3 py-1.5 text-right ${r.planted_ln_m_ltv >= 0 ? "text-scale" : "text-kill"}`}>
                      {r.planted_ln_m_ltv.toFixed(2)}
                    </td>
                    <td className={`px-3 py-1.5 text-right ${r.effect_value_usd >= 0 ? "text-scale" : "text-kill"}`}>
                      {r.effect_value_usd >= 0 ? "+" : "−"}${Math.abs(r.effect_value_usd).toFixed(0)}
                    </td>
                    <td className="px-3 py-1.5 text-right text-faint">{r.n.toLocaleString("en-US")}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title="The validate() gate">
        <P>
          The build refuses to ship unless the demo&apos;s guarantees hold. Current report (baked
          into the artifacts, regenerated on every <code>npm run generate</code>):
        </P>
        <ul className="space-y-1.5 text-sm mt-3">
          {[...v.core, ...v.stats].map((c) => (
            <li key={c.name} className="flex gap-2">
              <span className={c.pass ? "text-scale" : "text-trim"}>{c.pass ? "✓" : "⚠"}</span>
              <span>
                <span className="text-foreground">{c.name}</span>{" "}
                <span className="text-faint">— {c.detail}</span>
              </span>
            </li>
          ))}
        </ul>
        <P className="mt-3 text-xs">
          ⚠ items are disclosed tuning targets, not hidden failures — the core demo guarantees
          (both story cells, sparsity, finite numbers, honest headlines) are hard gates.
        </P>
      </Section>

      <Section title="Known limits — deliberately plain">
        <Ul
          items={[
            "Planted effects multiply independently; real targeting interacts in messier ways.",
            "Upside estimates assume flat marginal CAC and say so on every card.",
            `Uncertainty ranges are 80% (not 95%) and floor at ±${mult(Math.sqrt(THRESHOLDS.var_prior_floor) * THRESHOLDS.z80, 2)} — honest, not decorative.`,
            "The UNTAPPED call composes traits from a damped regression — it is a reason to test, never a reason to scale.",
            "Affiliate revenue is modeled per-subscriber; in production, network commissions often are not — the README covers the real ingestion rail.",
          ]}
        />
      </Section>
    </div>
  );
}

function pctOff(ratio: number): string {
  return `${Math.abs(Math.round((ratio - 1) * 100))}%`;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold">{title}</h2>
      {children}
    </section>
  );
}

function P({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <p className={`text-sm text-muted leading-relaxed ${className}`}>{children}</p>;
}

function Ol({ items }: { items: React.ReactNode[] }) {
  return (
    <ol className="space-y-2.5 text-sm text-muted leading-relaxed list-decimal ml-5">
      {items.map((it, i) => (
        <li key={i}>{it}</li>
      ))}
    </ol>
  );
}

function Ul({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className="space-y-1.5 text-sm text-muted leading-relaxed list-disc ml-5">
      {items.map((it, i) => (
        <li key={i}>{it}</li>
      ))}
    </ul>
  );
}

function Metric({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <div className="rounded-lg border border-line bg-surface px-4 py-3">
      <div className="text-2xl font-semibold">{value}</div>
      <div className="text-xs text-foreground mt-0.5">{label}</div>
      <div className="text-[10px] text-faint mt-0.5">{sub}</div>
    </div>
  );
}
